name: build
on: [push, workflow_dispatch]
jobs:

  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing dependencies
        run: sudo apt-get install -y openjdk-17-jdk libncurses5-dev libncursesw5-dev libtinfo5 cmake
  
      - name: Installing Cython
        run: pip3 install Cython<=3 --install-option="--no-cython-compile"
        
      - name: Installing buildozer
        run: pip3 install buildozer

      - name: Building APK
        run: buildozer -v android debug
          
      - name: Uploading Artifacts to Github
        uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: ./bin/group.dcindia.matrixcalc.apk
  
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Installing pyinstaller
        run: pip3 install pyinstaller
      
      - name: Installing kivy-deps
        run: pip3 install kivy-deps.sdl2 kivy-deps.glew

      - name: Installing Kivy/MD
        run: pip3 install kivy
        
      - name: Building EXE
        run: export KIVY_GL_BACKEND="angle_sdl2";
             pyinstaller ./.github/windows.spec
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: Windows EXE
          path: ./dist/Matrix Calculator.exe

  linux:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing Dependencies
        run: sudo apt-get install -y libmtdev1 libsdl2-2.0-0;  
      
      - name: Installing pyinstaller
        run: pip3 install pyinstaller

      - name: Installing Kivy
        run: pip3 install kivy kivymd
        
      - name: Building AppImage
        uses: coactions/setup-xvfb@v1
        with:
          run: pyinstaller ./.github/linux.spec --log-level DEBUG

      - name: Uploading Artifacts to Github
        uses: actions/upload-artifact@v3
        with:
          name: Linux AppImage
          path: ./dist/MatrixCalculator.AppImage
